[project]
name = "test-speed-scalesweep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "efsotr", email = "205368424@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
test-speed-scalesweep = "test_speed_scalesweep:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
